project:
  type: website
  output-dir: docs
  
website: 
  title: "Yutong Homepage"
  navbar:
    left:
      - href: index.qmd
        text: Use of glm
    #  - href: edu.qmd
    #    text: Education
      - href: ggplot2.qmd
        text: Use of ggplot2
    #  - href: onelayernn.qmd
    #    text: Machine Learning Methods 
format: 
  html: 
    theme: cosmo
    toc: true
